Repository flintlang/flint, pull requests merged in 2018-09, with the labels that each got.

#296 [FIP 0003] External Calls
  proposals/0003-external-calls.md
Labels: FIP

#335 Add quiet flag to supress warnings, and use for compiling behaviour t…
  Sources/flintc/Compiler.swift
  Sources/flintc/main.swift
  Tests/BehaviorTests/compile_behavior_tests.sh
Labels: review wanted

#334 Allow type state specifications to follow directly after contract nam…
  Sources/AST/Component/Attribute.swift
  Sources/Lexer/Lexer.swift
  Sources/Lexer/Token.swift
  Sources/Parser/Parser.swift
  Tests/SemanticTests/invalid_identifiers.flint
  Tests/SemanticTests/type_states.flint
  docs/grammar.abnf
Labels: review wanted

#329 Make sourceLocation indicators work with tabs not just spaces.
  Sources/Diagnostic/DiagnosticsFormatter.swift
Labels: review wanted

#316 Add candidate notes for initializer functions.
  Sources/AST/Declaration/SpecialDeclaration.swift
  Sources/AST/Environment/Environment+MatchFunction.swift
  Sources/AST/Environment/Environment+Type.swift
  Sources/AST/Environment/Information/CallableInformation.swift
  Sources/IRGen/Preprocessor/IRPreprocessor+Expressions.swift
  Sources/SemanticAnalyzer/SemanticAnalyzer+Expressions.swift
  Sources/SemanticAnalyzer/SemanticError.swift
  Tests/SemanticTests/inits.flint
Labels: review wanted

#327 Parser Errors
  Sources/AST/ASTPass/ASTPassRunner.swift
  Sources/AST/Environment/Environment+Memory.swift
  Sources/AST/Environment/Environment.swift
  Sources/AST/Environment/Information/PropertyInformation.swift
  Sources/AST/Expression/Expression.swift
  Sources/AST/Expression/RangeExpression.swift
  Sources/AST/Type.swift
  Sources/Diagnostic/DiagnosticPool.swift
  Sources/Diagnostic/DiagnosticsFormatter.swift
  Sources/Diagnostic/DiagnosticsVerifier.swift
  Sources/Diagnostic/SourceContext.swift
  Sources/IRGen/IREnum.swift
  Sources/Parser/Parser+Components.swift
  Sources/Parser/Parser+Declaration.swift
  Sources/Parser/Parser+Expressions.swift
  Sources/Parser/Parser+Statements.swift
  Sources/Parser/Parser+Utils.swift
  Sources/Parser/Parser.swift
  Sources/Parser/ParserError.swift
  Sources/Source/SourceLocation.swift
  Sources/flintc/Compiler.swift
  Sources/flintc/main.swift
Labels: merge priority

#354 Trait specification contracts
  Sources/AST/ASTDumper.swift
  Sources/AST/Declaration/ContractDeclaration.swift
  Sources/Parser/Parser+Components.swift
  Sources/Parser/Parser+Declaration.swift
  Sources/Parser/Parser.swift
  Sources/Parser/ParserError.swift
  Tests/ParserTests/conformance.flint
  docs/grammar.abnf
Labels: review wanted

#348 Allow Types to conform
  Sources/AST/Environment/Environment+Additions.swift
  Sources/AST/Environment/Environment+Checks.swift
  Sources/AST/Environment/Environment+MatchEvent.swift
  Sources/AST/Environment/Environment+MatchFunction.swift
  Sources/AST/Environment/Environment.swift
  Sources/AST/Environment/Information/TypeInformation.swift
Labels: review wanted

#357 Caller functions
  Sources/AST/ASTDumper.swift
  Sources/AST/Environment/Environment+Memory.swift
  Sources/AST/Environment/Environment+Type.swift
  Sources/AST/Environment/Environment.swift
  Sources/AST/TopLevelModule.swift
  Sources/AST/Type.swift
  Sources/IRGen/Runtime/IRCallerCapabilityChecks.swift
  Sources/IRGen/Runtime/IRWrapperFunction.swift
  Tests/BehaviorTests/tests/caller/caller.flint
  Tests/SemanticTests/caller_capability.flint
  Tests/SemanticTests/undeclared_capability.flint
Labels: review wanted

#374 Add flint paper to docs
  docs/flint.pdf
Labels: merge priority, merge wanted

#375 Add Franklin's thesis to docs
  docs/Franklin-Schrans-A-new-programming-language-for-safer-smart-contracts.pdf
Labels: merge wanted

#380 Skip malformed expressions
  Sources/Parser/Parser+Declaration.swift
Labels: bug, important, merge priority

#364 Move casestudies to common directory
  examples/casestudies/Bank.flint
  examples/casestudies/Factorial.flint
  examples/casestudies/SimpleAuction.flint
  examples/casestudies/SimpleDAO.flint
  examples/casestudies/Voting.flint
  examples/casestudies/Wallet.flint
  examples/casestudies/flightmanager/.gitignore
  examples/casestudies/flightmanager/FlightManager.flint
  examples/casestudies/flightmanager/config.js
  examples/casestudies/flightmanager/contracts/.FlightManager.flint
  examples/casestudies/flightmanager/migrations/1_initial_migration.js
  examples/casestudies/flightmanager/package.json
  examples/casestudies/flightmanager/truffle-config.js
  examples/casestudies/flightmanager/truffle.js
  examples/casestudies/flightmanager/web/flight-manager-ui/.gitignore
  examples/casestudies/flightmanager/web/flight-manager-ui/package.json
  examples/casestudies/flightmanager/web/flight-manager-ui/public/favicon.ico
  examples/casestudies/flightmanager/web/flight-manager-ui/public/index.html
  examples/casestudies/flightmanager/web/flight-manager-ui/public/manifest.json
  examples/casestudies/flightmanager/web/flight-manager-ui/src/App.css
  examples/casestudies/flightmanager/web/flight-manager-ui/src/App.js
  examples/casestudies/flightmanager/web/flight-manager-ui/src/App.test.js
  examples/casestudies/flightmanager/web/flight-manager-ui/src/abi.json
  examples/casestudies/flightmanager/web/flight-manager-ui/src/index.css
  examples/casestudies/flightmanager/web/flight-manager-ui/src/index.js
  examples/casestudies/flightmanager/web/flight-manager-ui/src/logo.png
  examples/casestudies/flightmanager/web/flight-manager-ui/src/registerServiceWorker.js
  examples/casestudies/token/ERC20-future.flint
  examples/casestudies/token/FlintToken.flint
  examples/casestudies/token/StandardToken.flint
Labels: review wanted

#385 Fix upload of build artifacts from travis to GitHub
  .travis.yml
Labels: review wanted

#395 Let parameters
  Sources/AST/ASTPass/ASTPassContext.swift
  Sources/AST/ASTVisitor/ASTVisitor.swift
  Sources/AST/Component/Parameter.swift
  Sources/AST/Environment/Environment+Type.swift
  Sources/AST/Type.swift
  Sources/IRGen/Component/IRAssignment.swift
  Sources/SemanticAnalyzer/SemanticAnalyzer+Components.swift
  Sources/SemanticAnalyzer/SemanticAnalyzer+Declarations.swift
  Tests/BehaviorTests/tests/array/array.flint
  Tests/SemanticTests/constants.flint
  Tests/SemanticTests/let_parameters.flint
Labels: merge wanted
