Repository flintlang/flint, pull requests merged in 2018-08, with the labels that each got.

#277 Parse Type State restrictions.
  Sources/AST/AST.swift
  Sources/AST/ASTDumper.swift
  Sources/AST/ASTPass.swift
  Sources/AST/ASTVisitor.swift
  Sources/AST/Environment.swift
  Sources/AST/Token.swift
  Sources/IRGen/IULIAPreprocessor.swift
  Sources/Optimizer/Optimizer.swift
  Sources/Parser/Parser.swift
  Sources/Parser/Tokenizer.swift
  Sources/SemanticAnalyzer/SemanticAnalyzer.swift
  Sources/SemanticAnalyzer/TypeChecker.swift
  Tests/ParserTests/type_states.flint
Labels: 0002-type-states, feature

#276 Support offset references in Diagnostics Verifier
  Sources/flintc/DiagnosticsVerifier.swift
  Tests/SemanticTests/events.flint
  Tests/SemanticTests/inits.flint
  Tests/SemanticTests/invalid_function_call.flint
  Tests/SemanticTests/invalid_types.flint
  Tests/SemanticTests/multi_dim_array.flint
  Tests/SemanticTests/no_associated_contract.flint
  Tests/SemanticTests/undeclared_identifiers.flint
Labels: feature, review wanted

#265 Add size property to arrays.
  Sources/AST/ASTVisitor.swift
  Sources/AST/Environment.swift
  Sources/IRGen/Function/IULIAExpression.swift
  Sources/IRGen/Runtime/IULIARuntimeFunction.swift
  Sources/SemanticAnalyzer/SemanticAnalyzer.swift
  Tests/BehaviorTests/tests/array/array.flint
  Tests/BehaviorTests/tests/array/test/test/test.js
Labels: merge wanted

#303 Use PATH lookup to locate solc binary.
  Sources/flintc/SolcCompiler.swift
Labels: merge wanted

#304 Fix misleading statePropertyUsedWithinPropertyInitializer error
  Sources/AST/Environment.swift
  Sources/SemanticAnalyzer/SemanticAnalyzer.swift
  Tests/SemanticTests/inits.flint
Labels: merge wanted

#245 Proposing FIP 0002 Type States
  proposals/0002-type-states.md
Labels: FIP

#287 [FIP-0002] Type States
  Sources/AST/AST.swift
  Sources/AST/ASTDumper.swift
  Sources/AST/ASTPass.swift
  Sources/AST/ASTPassContext.swift
  Sources/AST/ASTVisitor.swift
  Sources/AST/ASTVisitorContext.swift
  Sources/AST/Environment.swift
  Sources/AST/SourceLocation.swift
  Sources/AST/Token.swift
  Sources/IRGen/Function/IULIAExpression.swift
  Sources/IRGen/Function/IULIAFunction.swift
  Sources/IRGen/Function/IULIAStatement.swift
  Sources/IRGen/IULIAContract.swift
  Sources/IRGen/IULIAEnum.swift
  Sources/IRGen/IULIAPreprocessor.swift
  Sources/IRGen/Runtime/IULIAFunctionSelector.swift
  Sources/IRGen/Runtime/IULIARuntimeFunction.swift
  Sources/Optimizer/Optimizer.swift
  Sources/Parser/Parser.swift
  Sources/Parser/Tokenizer.swift
  Sources/SemanticAnalyzer/SemanticAnalyzer.swift
  Sources/SemanticAnalyzer/SemanticError.swift
  Sources/SemanticAnalyzer/TypeChecker.swift
  Sources/SemanticAnalyzer/TypeError.swift
  Tests/BehaviorTests/tests/enums/enums.flint
  Tests/BehaviorTests/tests/enums/test/config.js
  Tests/BehaviorTests/tests/enums/test/migrations/1.js
  Tests/BehaviorTests/tests/enums/test/test/.placeholder
  Tests/BehaviorTests/tests/enums/test/test/test.js
  Tests/BehaviorTests/tests/enums/test/truffle-config.js
  Tests/BehaviorTests/tests/enums/test/truffle.js
  Tests/BehaviorTests/tests/simpleDAO/simpleDAO.flint
  Tests/BehaviorTests/tests/simpleDAO/test/config.js
  Tests/BehaviorTests/tests/simpleDAO/test/migrations/1.js
  Tests/BehaviorTests/tests/simpleDAO/test/test/test.js
  Tests/BehaviorTests/tests/simpleDAO/test/truffle-config.js
  Tests/BehaviorTests/tests/simpleDAO/test/truffle.js
  Tests/ParserTests/become.flint
  Tests/ParserTests/enums.flint
  Tests/ParserTests/type_states.flint
  Tests/SemanticTests/enums.flint
  Tests/SemanticTests/events.flint
  Tests/SemanticTests/invalid_function_call.flint
  Tests/SemanticTests/invalid_types.flint
  Tests/SemanticTests/returns.flint
  Tests/SemanticTests/structs.flint
  Tests/SemanticTests/type_states.flint
  Tests/SemanticTests/undeclared_identifiers.flint
  Tests/SemanticTests/undeclared_type.flint
Labels: 0002-type-states, merge wanted

#311 Update Language grammar for Flint
  docs/grammar.abnf
  docs/grammar.txt
  docs/pull_request_template.md
Labels: feature, merge wanted

#299 Create BracketedExpression AST Node
  Sources/AST/AST.swift
  Sources/AST/ASTDumper.swift
  Sources/AST/ASTVisitor.swift
  Sources/AST/Environment.swift
  Sources/IRGen/Function/IULIAExpression.swift
  Sources/Parser/Parser.swift
  Tests/ParserTests/branching.flint
Labels: merge wanted

#259 Support Fallback function
  Sources/AST/AST.swift
  Sources/AST/ASTDumper.swift
  Sources/AST/ASTPass.swift
  Sources/AST/ASTPassContext.swift
  Sources/AST/ASTVisitor.swift
  Sources/AST/ASTVisitorContext.swift
  Sources/AST/Environment.swift
  Sources/AST/Token.swift
  Sources/IRGen/Function/IULIAContractInitializer.swift
  Sources/IRGen/Function/IULIAFallback.swift
  Sources/IRGen/IULIAContract.swift
  Sources/IRGen/IULIAInterface.swift
  Sources/IRGen/IULIAPreprocessor.swift
  Sources/IRGen/Runtime/IULIAFunctionSelector.swift
  Sources/Optimizer/Optimizer.swift
  Sources/Parser/Parser.swift
  Sources/Parser/Tokenizer.swift
  Sources/SemanticAnalyzer/SemanticAnalyzer.swift
  Sources/SemanticAnalyzer/SemanticError.swift
  Sources/SemanticAnalyzer/TypeChecker.swift
  Tests/BehaviorTests/tests/fallback/fallback.flint
  Tests/BehaviorTests/tests/fallback/test/config.js
  Tests/BehaviorTests/tests/fallback/test/migrations/1.js
  Tests/BehaviorTests/tests/fallback/test/test/test.js
  Tests/BehaviorTests/tests/fallback/test/truffle-config.js
  Tests/BehaviorTests/tests/fallback/test/truffle.js
  Tests/ParserTests/array.flint
  Tests/ParserTests/capability_binding.flint
  Tests/ParserTests/enums.flint
  Tests/ParserTests/literals.flint
  Tests/ParserTests/localvar.flint
  Tests/ParserTests/nested_branching.flint
  Tests/ParserTests/payable.flint
  Tests/ParserTests/structs.flint
  Tests/ParserTests/type_states.flint
  Tests/ParserTests/types.flint
  Tests/ParserTests/whitespace.flint
  Tests/SemanticTests/fallback.flint
Labels: feature, merge priority, merge wanted

#274 Add keys array to StorageDictionaries
  Sources/AST/ASTVisitor.swift
  Sources/AST/Environment.swift
  Sources/IRGen/Function/IULIAExpression.swift
  Sources/IRGen/Function/IULIAStatement.swift
  Sources/IRGen/Runtime/IULIAFunctionSelector.swift
  Sources/IRGen/Runtime/IULIARuntimeFunction.swift
  Tests/BehaviorTests/tests/array/test/test/test.js
  Tests/BehaviorTests/tests/bank/test/test/test.js
  Tests/BehaviorTests/tests/loop/loop.flint
  Tests/BehaviorTests/tests/loop/test/test/test.js
  Tests/SemanticTests/caller_capability.flint
Labels: merge priority, merge wanted

#301 Check operand types are compatible with operators
  Sources/AST/Environment.swift
  Sources/SemanticAnalyzer/TypeChecker.swift
  Sources/SemanticAnalyzer/TypeError.swift
  Tests/ParserTests/for.flint
  Tests/SemanticTests/enums.flint
  Tests/SemanticTests/operand_types.flint
Labels: merge priority, merge wanted

#318 Add attempt calls to grammar + remove unnecessary <> from abnf
  docs/grammar.abnf
Labels: merge wanted

#307 Accessors and Mutators for public and visible modifiers
  Sources/AST/ASTDumper.swift
  Sources/AST/ASTVisitor/ASTVisitor.swift
  Sources/AST/Component/Parameter.swift
  Sources/AST/Declaration/StructDeclaration.swift
  Sources/AST/Declaration/VariableDeclaration.swift
  Sources/AST/Environment/Environment+Additions.swift
  Sources/AST/TopLevelModule.swift
  Sources/IRGen/Function/IRContractInitializer.swift
  Sources/IRGen/Function/IRExpression.swift
  Sources/IRGen/Function/IRFallback.swift
  Sources/IRGen/Function/IRFunction.swift
  Sources/IRGen/Function/IRStatement.swift
  Sources/IRGen/IRCanonicalType.swift
  Sources/IRGen/IRCodeGenerator.swift
  Sources/IRGen/IRContract.swift
  Sources/IRGen/IREnum.swift
  Sources/IRGen/IRInterface.swift
  Sources/IRGen/IRStruct.swift
  Sources/IRGen/Preprocessor/IRPreprocessor+Expressions.swift
  Sources/IRGen/Preprocessor/IRPreprocessor.swift
  Sources/IRGen/Runtime/IRCallerCapabilityChecks.swift
  Sources/IRGen/Runtime/IRFunctionSelector.swift
  Sources/IRGen/Runtime/IRRuntimeFunction.swift
  Sources/IRGen/Runtime/IRWrapperFunction.swift
  Sources/IRGen/String+Indentation.swift
  Sources/Lexer/Lexer.swift
  Sources/Lexer/Token.swift
  Sources/Parser/Parser.swift
  Sources/SemanticAnalyzer/SemanticAnalyzer+Declarations.swift
  Sources/SemanticAnalyzer/SemanticError.swift
  Sources/Source/SourceLocation.swift
  Sources/flintc/Compiler.swift
  Sources/flintc/SolcCompiler.swift
  Tests/BehaviorTests/tests/synthesize/synthesize.flint
  Tests/BehaviorTests/tests/synthesize/test/config.js
  Tests/BehaviorTests/tests/synthesize/test/migrations/1.js
  Tests/BehaviorTests/tests/synthesize/test/synthesize.flint
  Tests/BehaviorTests/tests/synthesize/test/test/test.js
  Tests/BehaviorTests/tests/synthesize/test/truffle-config.js
  Tests/BehaviorTests/tests/synthesize/test/truffle.js
  Tests/ParserTests/variable_modifiers.flint
  Tests/SemanticTests/invalid_modifiers.flint
  docs/compiler_guide.md
Labels: merge wanted

#254 ERC20
  examples/solidity-translation/token/ERC20-future.flint
  examples/solidity-translation/token/FlintToken.flint
  examples/solidity-translation/token/StandardToken.flint
Labels: review wanted, solidity-translation

#326 Add separators to grammar
  docs/grammar.abnf
Labels: merge wanted
